# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: StuffToTest.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='StuffToTest.proto',
  package='',
  serialized_pb='\n\x11StuffToTest.proto\"\x80\x01\n\x08NumStuff\x12\x0b\n\x03i01\x18\x01 \x02(\x05\x12\x0b\n\x03i02\x18\x02 \x02(\x03\x12\x0b\n\x03\x64\x30\x33\x18\x03 \x02(\x01\x12\x14\n\x04\x65_04\x18\x04 \x02(\x0e\x32\x06.Enum4\x12\x0e\n\x06l1_i05\x18\x05 \x03(\x03\x12\x0e\n\x06l1_d06\x18\x06 \x03(\x01\x12\x17\n\x06l1_e07\x18\x07 \x03(\x0e\x32\x07.Enum16\"G\n\x0bStringStuff\x12\x0b\n\x03s01\x18\x01 \x02(\t\x12\x0b\n\x03\x62\x30\x32\x18\x02 \x02(\x0c\x12\x0e\n\x06l1_s03\x18\x03 \x03(\t\x12\x0e\n\x06l1_b04\x18\x04 \x03(\x0c\"\xbc\x01\n\nComboStuff\x12\x0b\n\x03i01\x18\x01 \x02(\x05\x12\x0b\n\x03i02\x18\x02 \x02(\x03\x12\x0b\n\x03\x64\x30\x33\x18\x03 \x02(\x01\x12\x14\n\x04\x65_04\x18\x04 \x02(\x0e\x32\x06.Enum4\x12\x0e\n\x06l1_i05\x18\x05 \x03(\x03\x12\x0e\n\x06l1_d06\x18\x06 \x03(\x01\x12\x17\n\x06l1_e07\x18\x07 \x03(\x0e\x32\x07.Enum16\x12\x0b\n\x03s08\x18\x08 \x02(\t\x12\x0b\n\x03\x62\x30\x39\x18\t \x02(\x0c\x12\x0e\n\x06l1_s10\x18\n \x03(\t\x12\x0e\n\x06l1_b11\x18\x0b \x03(\x0c\"\xcc\x01\n\nComboBunch\x12\x15\n\x04\x65_01\x18\x01 \x02(\x0e\x32\x07.Enum16\x12\x17\n\x04ns02\x18\x02 \x02(\x0b\x32\t.NumStuff\x12\x1a\n\x04ss03\x18\x03 \x02(\x0b\x32\x0c.StringStuff\x12\x19\n\x04\x63s04\x18\x04 \x02(\x0b\x32\x0b.ComboStuff\x12\x1a\n\x07l2_ns05\x18\x05 \x03(\x0b\x32\t.NumStuff\x12\x1d\n\x07l2_ss06\x18\x06 \x03(\x0b\x32\x0c.StringStuff\x12\x1c\n\x07l2_cs07\x18\x07 \x03(\x0b\x32\x0b.ComboStuff*3\n\x05\x45num4\x12\t\n\x05VAL_0\x10\x00\x12\t\n\x05VAL_1\x10\x01\x12\t\n\x05VAL_2\x10\x02\x12\t\n\x05VAL_3\x10\x03*\xc2\x01\n\x06\x45num16\x12\t\n\x05VAL_4\x10\x04\x12\t\n\x05VAL_5\x10\x05\x12\t\n\x05VAL_6\x10\x06\x12\t\n\x05VAL_7\x10\x07\x12\t\n\x05VAL_8\x10\x08\x12\t\n\x05VAL_9\x10\t\x12\n\n\x06VAL_10\x10\n\x12\n\n\x06VAL_11\x10\x0b\x12\n\n\x06VAL_12\x10\x0c\x12\n\n\x06VAL_13\x10\r\x12\n\n\x06VAL_14\x10\x0e\x12\n\n\x06VAL_15\x10\x0f\x12\n\n\x06VAL_16\x10\x10\x12\n\n\x06VAL_17\x10\x11\x12\n\n\x06VAL_18\x10\x12\x12\n\n\x06VAL_19\x10\x13')

_ENUM4 = _descriptor.EnumDescriptor(
  name='Enum4',
  full_name='Enum4',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='VAL_0', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VAL_1', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VAL_2', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VAL_3', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=623,
  serialized_end=674,
)

Enum4 = enum_type_wrapper.EnumTypeWrapper(_ENUM4)
_ENUM16 = _descriptor.EnumDescriptor(
  name='Enum16',
  full_name='Enum16',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='VAL_4', index=0, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VAL_5', index=1, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VAL_6', index=2, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VAL_7', index=3, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VAL_8', index=4, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VAL_9', index=5, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VAL_10', index=6, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VAL_11', index=7, number=11,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VAL_12', index=8, number=12,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VAL_13', index=9, number=13,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VAL_14', index=10, number=14,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VAL_15', index=11, number=15,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VAL_16', index=12, number=16,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VAL_17', index=13, number=17,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VAL_18', index=14, number=18,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VAL_19', index=15, number=19,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=677,
  serialized_end=871,
)

Enum16 = enum_type_wrapper.EnumTypeWrapper(_ENUM16)
VAL_0 = 0
VAL_1 = 1
VAL_2 = 2
VAL_3 = 3
VAL_4 = 4
VAL_5 = 5
VAL_6 = 6
VAL_7 = 7
VAL_8 = 8
VAL_9 = 9
VAL_10 = 10
VAL_11 = 11
VAL_12 = 12
VAL_13 = 13
VAL_14 = 14
VAL_15 = 15
VAL_16 = 16
VAL_17 = 17
VAL_18 = 18
VAL_19 = 19



_NUMSTUFF = _descriptor.Descriptor(
  name='NumStuff',
  full_name='NumStuff',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='i01', full_name='NumStuff.i01', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='i02', full_name='NumStuff.i02', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='d03', full_name='NumStuff.d03', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='e_04', full_name='NumStuff.e_04', index=3,
      number=4, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='l1_i05', full_name='NumStuff.l1_i05', index=4,
      number=5, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='l1_d06', full_name='NumStuff.l1_d06', index=5,
      number=6, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='l1_e07', full_name='NumStuff.l1_e07', index=6,
      number=7, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=22,
  serialized_end=150,
)


_STRINGSTUFF = _descriptor.Descriptor(
  name='StringStuff',
  full_name='StringStuff',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='s01', full_name='StringStuff.s01', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='b02', full_name='StringStuff.b02', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='l1_s03', full_name='StringStuff.l1_s03', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='l1_b04', full_name='StringStuff.l1_b04', index=3,
      number=4, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=152,
  serialized_end=223,
)


_COMBOSTUFF = _descriptor.Descriptor(
  name='ComboStuff',
  full_name='ComboStuff',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='i01', full_name='ComboStuff.i01', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='i02', full_name='ComboStuff.i02', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='d03', full_name='ComboStuff.d03', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='e_04', full_name='ComboStuff.e_04', index=3,
      number=4, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='l1_i05', full_name='ComboStuff.l1_i05', index=4,
      number=5, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='l1_d06', full_name='ComboStuff.l1_d06', index=5,
      number=6, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='l1_e07', full_name='ComboStuff.l1_e07', index=6,
      number=7, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='s08', full_name='ComboStuff.s08', index=7,
      number=8, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='b09', full_name='ComboStuff.b09', index=8,
      number=9, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='l1_s10', full_name='ComboStuff.l1_s10', index=9,
      number=10, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='l1_b11', full_name='ComboStuff.l1_b11', index=10,
      number=11, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=226,
  serialized_end=414,
)


_COMBOBUNCH = _descriptor.Descriptor(
  name='ComboBunch',
  full_name='ComboBunch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='e_01', full_name='ComboBunch.e_01', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=4,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ns02', full_name='ComboBunch.ns02', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ss03', full_name='ComboBunch.ss03', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cs04', full_name='ComboBunch.cs04', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='l2_ns05', full_name='ComboBunch.l2_ns05', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='l2_ss06', full_name='ComboBunch.l2_ss06', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='l2_cs07', full_name='ComboBunch.l2_cs07', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=417,
  serialized_end=621,
)

_NUMSTUFF.fields_by_name['e_04'].enum_type = _ENUM4
_NUMSTUFF.fields_by_name['l1_e07'].enum_type = _ENUM16
_COMBOSTUFF.fields_by_name['e_04'].enum_type = _ENUM4
_COMBOSTUFF.fields_by_name['l1_e07'].enum_type = _ENUM16
_COMBOBUNCH.fields_by_name['e_01'].enum_type = _ENUM16
_COMBOBUNCH.fields_by_name['ns02'].message_type = _NUMSTUFF
_COMBOBUNCH.fields_by_name['ss03'].message_type = _STRINGSTUFF
_COMBOBUNCH.fields_by_name['cs04'].message_type = _COMBOSTUFF
_COMBOBUNCH.fields_by_name['l2_ns05'].message_type = _NUMSTUFF
_COMBOBUNCH.fields_by_name['l2_ss06'].message_type = _STRINGSTUFF
_COMBOBUNCH.fields_by_name['l2_cs07'].message_type = _COMBOSTUFF
DESCRIPTOR.message_types_by_name['NumStuff'] = _NUMSTUFF
DESCRIPTOR.message_types_by_name['StringStuff'] = _STRINGSTUFF
DESCRIPTOR.message_types_by_name['ComboStuff'] = _COMBOSTUFF
DESCRIPTOR.message_types_by_name['ComboBunch'] = _COMBOBUNCH

class NumStuff(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _NUMSTUFF

  # @@protoc_insertion_point(class_scope:NumStuff)

class StringStuff(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STRINGSTUFF

  # @@protoc_insertion_point(class_scope:StringStuff)

class ComboStuff(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _COMBOSTUFF

  # @@protoc_insertion_point(class_scope:ComboStuff)

class ComboBunch(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _COMBOBUNCH

  # @@protoc_insertion_point(class_scope:ComboBunch)


# @@protoc_insertion_point(module_scope)
